name: Update all themes

on:
  workflow_dispatch:
  schedule:
    - cron: "51 5 * * 1"

jobs:
  update-all-themes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Update submodules
        run: "git submodule update --remote"
      - name: Commit, push and generate
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git status
          if [[ `git status --short` ]]; then
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"
            git commit -am "Update all themes"
            git push
            gh workflow run generate.yml
          fi
